// @volatile: Keep in sync with constants declared in Renderer and Renderer2D.

#define ZTH_DIFFUSE_MAP_SLOT 0
#define ZTH_SPECULAR_MAP_SLOT 1
#define ZTH_EMISSION_MAP_SLOT 2

#define ZTH_TEXTURE_2D_SLOT 0

#define ZTH_CAMERA_UBO_BINDING_POINT 0
#define ZTH_MATERIAL_UBO_BINDING_POINT 1

#define ZTH_DIRECTIONAL_LIGHTS_SSBO_BINDING_POINT 0
#define ZTH_POINT_LIGHTS_SSBO_BINDING_POINT 1
#define ZTH_SPOT_LIGHTS_SSBO_BINDING_POINT 2
#define ZTH_AMBIENT_LIGHTS_SSBO_BINDING_POINT 3