name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.preset.name }}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        preset:
          - { name: x64 Debug, configure: x64-debug, build: x64-debug-build, test: x64-debug-test }
          - { name: x64 Release, configure: x64-release, build: x64-release-build, test: x64-release-test  }
          - { name: x64 Dist, configure: x64-dist, build: x64-dist-build, test: x64-dist-test  }

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Configure
      run: cmake -B build --preset ${{ matrix.preset.configure }} -G "Visual Studio 17 2022"

    - name: Build
      run: cmake --build build --preset ${{ matrix.preset.build }}

    - name: Test
      run: ctest --preset ${{ matrix.preset.test }}
