name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.preset.name }}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        preset:
          - { name: x64-debug }
          - { name: x64-release }
          - { name: x64-dist }

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Configure
      run: cmake -B build --preset ${{ matrix.preset.name }} -G "Visual Studio 17 2022"

    - name: Build
      run: cmake --build build --preset ${{ matrix.preset.name }}

    - name: Test
      run: ctest --preset ${{ matrix.preset.name }}
