name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        config: # Values based on presets defined in CMakePresets.json
          - { name: debug, build_type: Debug, flags:                          -DZTH_DEVELOPER=TRUE -DZTH_ASSERTIONS=TRUE  -DZTH_GL_DEBUG=TRUE  -DZTH_DEBUG_LOGGING=TRUE  -DZTH_PROFILER=TRUE }
          - { name: optimized-debug, build_type: RelWithDebInfo, flags:       -DZTH_DEVELOPER=TRUE -DZTH_ASSERTIONS=TRUE  -DZTH_GL_DEBUG=TRUE  -DZTH_DEBUG_LOGGING=TRUE  -DZTH_PROFILER=TRUE }
          - { name: development, build_type: RelWithDebInfo, flags:           -DZTH_DEVELOPER=TRUE -DZTH_ASSERTIONS=FALSE -DZTH_GL_DEBUG=TRUE  -DZTH_DEBUG_LOGGING=TRUE  -DZTH_PROFILER=TRUE }
          - { name: profile, build_type: RelWithDebInfo, flags:               -DZTH_DEVELOPER=TRUE -DZTH_ASSERTIONS=FALSE -DZTH_GL_DEBUG=FALSE -DZTH_DEBUG_LOGGING=FALSE -DZTH_PROFILER=TRUE }
          - { name: release-with-deb-info, build_type: RelWithDebInfo, flags: -DZTH_DEVELOPER=TRUE -DZTH_ASSERTIONS=FALSE -DZTH_GL_DEBUG=FALSE -DZTH_DEBUG_LOGGING=FALSE -DZTH_PROFILER=FALSE }
          - { name: release, build_type: Release, flags:                      -DZTH_DEVELOPER=TRUE -DZTH_ASSERTIONS=FALSE -DZTH_GL_DEBUG=FALSE -DZTH_DEBUG_LOGGING=FALSE -DZTH_PROFILER=FALSE }

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} ${{ matrix.config.flags }}

    - name: Build
      run: cmake --build build --config ${{ matrix.config.build_type }}

    - name: Test
      if: ${{ matrix.config.build_type == 'Debug' }}
      run: ctest --test-dir build --build-config ${{ matrix.config.build_type }}
