name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: Debug, build_type: Debug, flags: -DZTH_DIST_BUILD=FALSE }
          - { name: Release, build_type: RelWithDebInfo, flags: -DZTH_DIST_BUILD=FALSE }
          - { name: Dist, build_type: Release, flags: -DZTH_DIST_BUILD=TRUE }

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} ${{ matrix.config.flags }}

    - name: Build
      run: cmake --build build --config ${{ matrix.config.build_type }}

    - name: Test
      if: matrix.config.build_type == "Debug"
      run: ctest --config ${{ matrix.config.build_type }}
